### ISSUE TITLE
Except for StrictUndefined 

### ISSUE THREAD

**Issue by sergei-sss** [jg-rp/liquid#110]
Is it possible to add the specific variable(s) to exception list for current undefined mode?

I use StrictUndefined mode for Environment, but It's needed to convert specific variable `{{unsubscribe_link}}` to `{{amazonSESUnsubscribeUrl}}` for email template (`{{amazonSESUnsubscribeUrl}}` value will be converted by AWS SES on email sending).

**Comment by jg-rp** [comment]
Hi @sergei-sss,

You could just define these variables as [Environment](https://jg-rp.github.io/liquid/introduction/render-context#environment-globals) and/or [Template](https://jg-rp.github.io/liquid/introduction/render-context#template-globals) globals, where their value is the AWS SES placeholder string, including `{{` and `}}`.

```python
from liquid import Environment
from liquid import StrictUndefined

passthrough = {
    "unsubscribe_link": "{{amazonSESUnsubscribeUrl}}",
    # Add more here.
}

env = Environment(undefined=StrictUndefined, globals=passthrough)

template = env.from_string('<a href="{{ unsubscribe_link }}">Unsubscribe</a>')
print(template.render())
```

**output**
```liquid
<a href="{{amazonSESUnsubscribeUrl}}">Unsubscribe</a>
```

An alternative using a custom `Undefined` type can get a little messy.

**Comment by jg-rp** [comment]
Another option is to subclass `liquid.Context` and override `_resolve()`. This has the advantage that template authors can never redefine these variables using `{% assign %}`.

```python
from typing import Any

from liquid import BoundTemplate
from liquid import Context
from liquid import Environment
from liquid import StrictUndefined

class MyRenderContext(Context):
    passthrough = {
        "unsubscribe_link": "{{amazonSESUnsubscribeUrl}}",
        # Add more here.
    }

    def _resolve(self, name: str, default: object = ...) -> Any:
        try:
            return self.passthrough[name]
        except KeyError:
            return super()._resolve(name, default)


class MyTemplate(BoundTemplate):
    context_class = MyRenderContext


class MyEnvironment(Environment):
    template_class = MyTemplate


env = MyEnvironment(undefined=StrictUndefined)

template = env.from_string('<a href="{{ unsubscribe_link }}">Unsubscribe</a>')
print(template.render())
```

**Comment by sergei-sss** [comment]
@jg-rp Thanks a lot for the detailed answer!
