### ISSUE TITLE
Newline rendering bug

### ISSUE THREAD

**Issue by mkozakov** [jg-rp/liquid#127]
**Description**

If `\n` is the only character in a block, it doesn't get rendered.

**Example**

```python
t = Template("Hello{% if true %}\n{% endif %}Goodbye")
t.render()
```

produces

```
HelloGoodbye
```
instead of 

```
Hello
Goodbye
```

This breaks templates with for loops that add a newline for all iterations except the last one.

**Comment by jg-rp** [comment]
Hi @mkozakov,

The behaviour demonstrated by your example is deliberate and is consistent with Shopify/Liquid, the reference implementation.

`{% case %}`, `{% for %}`, `{% if %}` and `{% unless %}` tags will all suppress blocks that contain only whitespace. I'm open to adding an [`Environment`](https://jg-rp.github.io/liquid/api/Environment) option to disable this behaviour.

Or, if you can provide another example of your use case including a `for` loop, there might be a workaround using existing features.

**Comment by mkozakov** [comment]
The template we're working with looks something like this:

```
{% for message in messages %}{{ message.text }}{% unless forloop.last %}\n{% endunless %}{% endfor %}
```

The workaround we found is wrapping `\n` in `{{ '\n' }}`, but wondering if there is a cleaner way of doing this

**Comment by jg-rp** [comment]
Your workaround looks like the best option when you're restricted to "standard" Liquid.

If you're not concerned with interoperability with Shopify/Liquid, as of Python Liquid version 1.10.0, you can disable suppression of whitespace only blocks by setting the `render_whitespace_only_blocks` class attribute on an `Environment` subclass to `True`. This affects all block tags.

```python
from liquid import Environment

class MyEnvironment(Environment):
    render_whitespace_only_blocks = True

env = MyEnvironment()
template = env.from_string("Hello{% if true %}\n\n{% endif %}World!")
print(template.render())
```

**Output**
```plain
Hello

World!
```

Or, to disable whitespace suppression for just the `{% unless %}` tag, you could use the `force_output` attribute on an `UnlessNode` subclass. This also requires Python Liquid version 1.10.0 or later.

```python
from liquid import Environment
from liquid.builtin.tags.unless_tag import UnlessNode
from liquid.builtin.tags.unless_tag import UnlessTag

class MyUnlessNode(UnlessNode):
    force_output = True


class MyUnlessTag(UnlessTag):
    node_class = MyUnlessNode


env = Environment()
env.add_tag(MyUnlessTag)

template = env.from_string(
    "{% for x in (1..3) %}"
    "{{ x }}"
    "{% unless forloop.last %}\n{% endunless %}"
    "{% endfor %}"
)

result = template.render() # "1\n2\n3"
```

There's a [new docs page](https://jg-rp.github.io/liquid/guides/whitespace-suppression) describing this too.
