### ISSUE TITLE
Add Cached ChoiceLoader 

### ISSUE THREAD

**Issue by chaseastewart** [jg-rp/liquid#139]
Maybe something like [this](https://github.com/chaseastewart/fhir-converter/blob/main/fhir_converter/loaders.py#L15)?

**Comment by jg-rp** [comment]
Hi @chaseastewart,

That's a good idea.  Pull requests are welcome, otherwise it'll probably be a week or two before I get around to it.

**Comment by jg-rp** [comment]
`CachingChoiceLoader` is available in Python Liquid version 1.11.0, now released. 

[docs](https://jg-rp.github.io/liquid/api/cachingchoiceloader), [source](https://github.com/jg-rp/liquid/blob/main/liquid/builtin/loaders/choice_loader.py#L114)

**Comment by chaseastewart** [comment]
@jg-rp [148](Logged https://github.com/jg-rp/liquid/issues/148). This also applies to CachingFileSystemLoader.
