### ISSUE TITLE
Security guarantees

### ISSUE THREAD

**Issue by taylor-cedar** [jg-rp/liquid#48]
I am wondering if this library has the same security guarantees as the Ruby version. If I run an untrusted template from a client, is it dangerous? Is security a design goal in addition to the API compatibility?

**Comment by jg-rp** [comment]
Hi,

Python Liquid has indeed been designed and implemented with the same security goals as Ruby Liquid. Notably:

- Python Liquid is non-evaling. That is, it does not use [`eval`](https://docs.python.org/3/library/functions.html#eval) in any way whatsoever.
- Python Liquid does **not** compile templates to Python code, as you might be familiar with from [Jinja2](https://github.com/pallets/jinja/).
- Python Liquid will never call functions or methods on arbitrary objects (drops) added to a render context. Instead relying on the [Mapping  interface](https://jg-rp.github.io/liquid/introduction/objects-and-drops).
- Python Liquid creates a new render context for every template so data does not leak from one template to another.
- Template local and global variables use isolated namespaces, so templates can't mutate "global" data.
- All built-in filters are pure, so they can't mutate global data either.

It's still entirely possible for developers to deploy an application using Python Liquid in an "unsafe" way. Here I'm thinking of custom filters or tags that don't respect the template global namespace, or "drops" that do impure things with some of Python's [magic methods](https://docs.python.org/3/reference/datamodel.html#basic-customization). And, of course, all sorts of user input will need to be [escaped](https://jg-rp.github.io/liquid/introduction/auto-escape) when handling HTML templates.

Adding something to this effect to the documentation is on my to-do list. As is a security policy for the GitHub repository.

**Comment by taylor-cedar** [comment]
Thanks @jg-rp. That is really helpful. Really appreciate all your hard work on this library. It's amazing.

**Comment by jg-rp** [comment]
You are welcome, @taylor-cedar.

Find the new security guidelines at https://jg-rp.github.io/liquid/guides/security, and the security policy at https://github.com/jg-rp/liquid/blob/main/.github/SECURITY.md.
