### ISSUE TITLE
StrictDefaultUndefined ignores undefined variables in filters other than default

### ISSUE THREAD

**Issue by hardiksondagar** [jg-rp/liquid#62]
The recently introduced `StrictDefaultUndefined` mode works perfectly with the `default` filter, but it's ignoring undefined variables in other filters. 
```
from liquid import Environment
from liquid import StrictDefaultUndefined

env = Environment(undefined=StrictDefaultUndefined)
template = env.from_string('Hello {{ username | floor }}')
print(template.render())

Hello 0
```

**Comment by jg-rp** [comment]
Hi @hardiksondagar,

Thank you for letting me know. `StrictDefaultUndefined` has been fixed in version 1.4.1, and I've been more thorough with the test cases this time.

**Comment by hardiksondagar** [comment]
Thanks a lot, @jg-rp for quick fixes. Let me know how I can start contributing to the project and maybe you can point me to the contribution guide if it's available.

**Comment by jg-rp** [comment]
Your contributions would be most welcome. I've started some [contributing guidelines](https://github.com/jg-rp/liquid/blob/main/contributing.md) and done some [workflow](https://github.com/jg-rp/liquid/actions) maintenance in anticipation.

Most of my own efforts will be focused on [Liquid Babel](https://github.com/jg-rp/liquid-babel) and getting feature parity between Python Liquid and [LiquidScript](https://github.com/jg-rp/liquidscript).

**Comment by hardiksondagar** [comment]
Hi @jg-rp, the default filter with `v1.4.1` is ignoring zero value.
```
from liquid import Environment
from liquid import StrictDefaultUndefined

env = Environment(undefined=StrictDefaultUndefined)
template = env.from_string('My value is {% assign var_x = 0 %} {{ var_x | default: "hello"}}')
print(template.render())

# with allow_false parameter
template = env.from_string('My value is {% assign var_x = 0 %} {{ var_x | default: "hello", allow_false: true}}')
print(template.render())

--
My value is hello
My value is hello
```
