### ISSUE TITLE
Template.analyze's representation of variables is lossy

### ISSUE THREAD

**Issue by brian-vanderford** [jg-rp/liquid#87]
````
>>> from liquid import Environment
>>> env = Environment()      
>>> env.from_string("{{thing['foo.bar']}}").analyze().variables # property "foo.bar" of thing
{'thing.foo.bar': [('<string>', 1)]}
>>> env.from_string("{{thing.foo.bar]}}").analyze().variables   # property bar of property foo of thing
{'thing.foo.bar': [('<string>', 1)]}
````

`thing['foo.bar']` and `thing.foo.bar` are distinct, but end up with the same representation.  It would be helpful to be able to get a more structured representation (maybe with a keyword arg to analyze) so that `thing['foo.bar']` is something like `('thing', 'foo.bar')` and `thing.foo.bar` `('thing', 'foo', 'bar')`.

**Comment by jg-rp** [comment]
Hi @brian-vanderford,

The string representation of variables has been fixed in version 1.6.0, and those strings now include a `parts` property, being a tuple representation of the variable. No extra arguments to `analyze()` required.

```python
from liquid import Environment

env = Environment()
template = env.from_string("{{ thing.foo.bar }} {{ thing['foo.bar'] }}")

for var, location in template.analyze().variables.items():
    for template_name, line_number in location:
        print(f"{var} {var.parts} found in '{template_name}' on line {line_number}")
```
**output**
```plain
thing.foo.bar ('thing', 'foo', 'bar') found in '<string>' on line 1
thing["foo.bar"] ('thing', 'foo.bar') found in '<string>' on line 1
```
